services:
  db:
    image: mysql:8.0
    container_name: cyna-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: cyna
      MYSQL_USER: cyna_user
      MYSQL_PASSWORD: cyna_password
      MYSQL_ROOT_PASSWORD: root_secure_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Optionnel : décommente la ligne suivante si tu as le fichier init.sql dans ton dossier
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cyna_network

  adminer:
    image: adminer
    container_name: cyna-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - cyna_network

volumes:
  db_data:

networks:
  cyna_network:
    driver: bridge
